DjangoChatBot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot_app.urls')),
    path('auth/', include('autentication.urls')),
    path('evaluation/', include('evaluation.urls')),
]

evaluation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('results/', views.evaluation_results, name='evaluation_results'),
    path('chart/', views.chart_results, name='chart_results'),
    path('update_rating/', views.update_user_rating, name='update_user_rating'),
]

evaluation/models.py
from django.db import models
from django.contrib.auth.models import User
from chatbot_app.models import PredefinedAnswer

class Evaluation(models.Model):
    USER_RATING_CHOICES = [
        ('U', 'Útil'),
        ('N', 'No útil'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.ForeignKey(PredefinedAnswer, on_delete=models.SET_NULL, null=True, blank=True)
    gpt_answer = models.TextField(blank=True, null=True)
    user_rating_choice = models.CharField(max_length=1, choices=USER_RATING_CHOICES, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.question}"

evaluation/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import user_passes_test
from .models import Evaluation
from chatbot_app.models import PredefinedAnswer
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
from datetime import datetime
from collections import defaultdict

@user_passes_test(lambda user: user.is_staff, login_url='login')
def evaluation_results(request):
    evaluations_list = Evaluation.objects.all().order_by('-timestamp')
    paginator = Paginator(evaluations_list, 10)
    page = request.GET.get('page')
    evaluations = paginator.get_page(page)

    context = {
        'evaluations': evaluations,
    }
    return render(request, 'evaluation/evaluation_results.html', context)

@user_passes_test(lambda user: user.is_staff, login_url='login')
def chart_results(request):
    start_date_str = request.GET.get('start_date')
    end_date_str = request.GET.get('end_date')
    if start_date_str:
        start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
    else:
        start_date = None
    if end_date_str:
        end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
    else:
        end_date = None
    evaluations_list = Evaluation.objects.all().order_by('-timestamp')

    # Aplicar filtros de fecha de inicio y fecha de finalización por separado
    if start_date:
        evaluations_list = evaluations_list.filter(timestamp__gte=start_date)
    if end_date:
        evaluations_list = evaluations_list.filter(timestamp__lte=end_date)

    paginator = Paginator(evaluations_list, 10)
    page = request.GET.get('page')
    evaluations = paginator.get_page(page)

    chart_data = generate_chart_data(start_date=start_date, end_date=end_date)

    context = {
        'evaluations': evaluations,
        'chart_data': json.dumps(chart_data),
        'start_date': start_date_str,
        'end_date': end_date_str,
    }
    return render(request, 'evaluation/chart_results.html', context)


@csrf_exempt
def update_user_rating(request):
    if request.method == "POST":
        data = json.loads(request.body)
        evaluation_id = data.get('evaluation_id')
        user_rating_choice = data.get('user_rating_choice')

        evaluation = Evaluation.objects.get(id=evaluation_id)
        evaluation.user_rating_choice = user_rating_choice
        evaluation.save()

        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "failed"})

def generate_chart_data(start_date, end_date):
    evaluations = Evaluation.objects.all().order_by('timestamp')

    if start_date:
        evaluations = evaluations.filter(timestamp__gte=start_date)
    if end_date:
        evaluations = evaluations.filter(timestamp__lte=end_date)

    chart_data = defaultdict(lambda: {"U": 0, "N": 0, "NE": 0})
    for evaluation in evaluations:
        date = evaluation.timestamp.date()
        user_rating_choice = evaluation.user_rating_choice if evaluation.user_rating_choice else "NE"
        chart_data[date][user_rating_choice] += 1

    labels = []
    useful_ratings = []
    not_useful_ratings = []
    not_evaluated_ratings = []

    for date, counts in chart_data.items():
        labels.append(date.strftime('%Y-%m-%d'))
        useful_ratings.append(counts["U"])
        not_useful_ratings.append(counts["N"])
        not_evaluated_ratings.append(counts["NE"])

    context = {
        'labels': labels,
        'useful_ratings': useful_ratings,
        'not_useful_ratings': not_useful_ratings,
        'not_evaluated_ratings': not_evaluated_ratings,
    }
    return context

templates/evaluation/chart_results.html
{% extends 'layout/base.html' %}
{% block 'title' %}Gráfico{% endblock %}
{% block 'content'  %}
<main class="main-content">
  <div class="container">
    <h2>Gráfico de valoraciones en respuestas</h2>
    <div class="row">
      <div class="col-md-4">
        <label for="start-date">Fecha de inicio:</label>
        <input type="date" id="start-date" name="start-date" class="form-control">
      </div>
      <div class="col-md-4">
        <label for="end-date">Fecha de fin:</label>
        <input type="date" id="end-date" name="end-date" class="form-control">
      </div>
      <div class="col-md-4">
        <label>&nbsp;</label>
        <button type="button" class="btn btn-primary" onclick="updateChartData()">Actualizar</button>
      </div>
    </div>
    <canvas id="evaluationChart" width="150" height="65"></canvas>
    <script id="chart-data" type="application/json">{{ chart_data }}</script>
  </div>
</main>
{% endblock %}

{% block 'scripts' %}
{% load static %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="{% static 'js/evaluation_charts.js' %}"></script>
{% endblock %}

templates/evaluation/evaluation_results.html
{% extends 'layout/base.html' %}
{% block 'title' %}Resultados{% endblock %}
{% block 'content'  %}
  <div class="container">
    <h1>Resultados de la evaluación</h1>
    <table class="table table-striped mt-2">
      <thead>
        <tr>
          <th scope="col">Usuario</th>
          <th scope="col">Pregunta</th>
          <th scope="col">Respuesta predefinida</th>
          <th scope="col">Respuesta GPT</th>
          <th scope="col">Valoración del usuario</th>
          <th scope="col">Fecha y hora</th>
        </tr>
      </thead>
      <tbody>
        {% for evaluation in evaluations %}
          <tr>
            <td>{{ evaluation.user.username }}</td>
            <td>{{ evaluation.question }}</td>
            <td>
              {% if evaluation.answer %}
                {{ evaluation.answer }}
              {% else %}
                N/A
              {% endif %}
            </td>
            <td>
              {% if evaluation.answer %}
                N/A
              {% else %}
                {{ evaluation.gpt_answer }}
              {% endif %}
            </td>
            <td>{{ evaluation.get_user_rating_choice_display }}</td>
            <td>{{ evaluation.timestamp }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="pagination">
      <span class="step-links">
        {% if evaluations.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ evaluations.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
          Page {{ evaluations.number }} of {{ evaluations.paginator.num_pages }}.
        </span>
        {% if evaluations.has_next %}
          <a href="?page={{ evaluations.next_page_number }}">next</a>
          <a href="?page={{ evaluations.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
{% endblock %}

{% block 'scripts' %}
{% load static %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="{% static 'js/evaluation_charts.js' %}"></script>
{% endblock %}